name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: [1.20]

    steps:
    - name: Set up Go ${{ matrix.goVer }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.goVer }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 1
        path: go/src/github.com/gophish/gophish

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get gopkg.in/check.v1
      env:
        GOPATH: /home/runner/work/gophish/go

    - name: Build
      run: go build -v .
    
    - name: Format
      run: diff -u <(echo -n) <(gofmt -d .)
    
    - name: Test
      run: go test -v ./...
